#!/usr/bin/env bash

# File generated by script.
TARGET=version.h

command -v git >/dev/null 2>&1 || {
    echo >&2 "GIT not available in PATH.";
    exit 1;
}

GIT_TAG=$(git describe --first-parent 2> /dev/null)
VERSION=$(expr "$GIT_TAG" : 'v\([0-9]\+.[0-9]\+.[0-9]\+\)')
VERSION_MAJOR=$(expr "$GIT_TAG" : 'v\([0-9]\+\)')
VERSION_MINOR=$(expr "$GIT_TAG" : 'v[0-9]\+.\([0-9]\+\)')
VERSION_PATCH=$(expr "$GIT_TAG" : 'v[0-9]\+.[0-9]\+.\([0-9]\+\)')
VERSION_HASH=$(git rev-parse --short HEAD 2> /dev/null)
VERSION_UNIXTIME=$(git show --quiet --format=%ct 2> /dev/null)

echo "\
#ifndef UTIL_META_VERSION_H
#define UTIL_META_VERSION_H

/// Project version information.
///
/// This file is generated from a shell script. Do not edit directly.
///
/// \\\\file

/// Project version, as C string on the form \`MAJOR.MINOR.PATCH\`.
#define META_VERSION \"$VERSION\"

/// Project major version, as integer.
#define META_VERSION_MAJOR $VERSION_MAJOR

/// Project minor version, as integer.
#define META_VERSION_MINOR $VERSION_MINOR

/// Project patch version, as integer.
#define META_VERSION_PATCH $VERSION_PATCH

/// Project version hash, as C string.
#define META_VERSION_HASH \"$VERSION_HASH\"

/// Project version creation time, as seconds since 1970-01-01 00:00:00.
#define META_VERSION_UNIXTIME $VERSION_UNIXTIME

#endif" > $TARGET
